#   +------------------------------------------------------+   #
#  /     __________      _______________       ____         \  #
# |     / ________/      \_____   _____/      / __ \         | #
# |    | /                     | |           / /  \ \        | #
# |    | |  _______            | |          / /____\ \       | #
# |    | |  \_____ \           | |         / ________ \      | #
# |    | \_______/ ||          | |        / /        \ \     | #
# |     \__________/           |_|       /_/          \_\    | #
# |                                                          | #
# |                    File: settings.yml                    | #
# |                  Author: [LuckyRaven10]                  | #
#  \                                                        /  #
#   +------------------------------------------------------+   #

# +----------------------------------+ #
# |      Settings Configuration      | #
# +----------------------------------+ #

# +---------------+ #
# | Update Config | #
# +---------------+ #

# If you have faced any problem with the file you can create a new one by changing [Config_Version] to a different
# number, but when a new update comes out with a new configuration file(s), [Config_Version] will change resulting
# in a new file(s) for that new version while saving old files with a suffix -old to indicate they are old.
## | WARNING |
# BY CHANGING [Config_Version] YOU WILL NEED TO CHANGE LINKED FILES TO IT [Config_Version] TOO JUST TO AVOID ERRORS.
# THIS OPTION IS EXPERIMENTAL AND WILL TAKE SOME TIME TILL I FIGURE A SOLUTION FOR IT!
# CHANGE IT IF YOU KNOW WHAT YOU ARE DOING!
Config_Version: 0
# We recommend to leave it true so people that got the permission will receive an update message.
Show_Update: true # This will work next update. An update will release immediately.

# +-----------------+ #
# | Language Config | #
# +-----------------+ #

# Messages language type. You can create a custom language by simply creating a folder called 'message' and inside it
# the language. You should respect the prefix of the file name, it should be message_xx.yml, and xx can be any letter
# you prefer. To switch between the languages, you enter the xx values in 'Language' and it would load that
# configuration.
# Any faulty written language names entered this attribute 'Language', then the plugin would disable. To make the plugin
# work just use any valid language. To get the list of the available languages, just enter an invalid name, and a
# message of the available list suffix would be displayed.
Language: en

# +-----------------+ #
# | Database Config | #
# +-----------------+ #
Database:
   # Specify which type of database to be used, [mysql, sqlite]
   Type: mysql
   MySQL:
      # Necessary credentials to enter your database
      Host: localhost
      Port: 3306
      Username: root
      Password: ""
   SQLite:
      # Will create a backup if the type is mysql
      Backup: true
