#   +------------------------------------------------------+   #
#  /     __________      _______________       ____         \  #
# |     / ________/      \_____   _____/      / __ \         | #
# |    | /                     | |           / /  \ \        | #
# |    | |  _______            | |          / /____\ \       | #
# |    | |  \_____ \           | |         / ________ \      | #
# |    | \_______/ ||          | |        / /        \ \     | #
# |     \__________/           |_|       /_/          \_\    | #
# |                                                          | #
# |                    File: settings.yml                    | #
# |                  Author: [LuckyRaven10]                  | #
#  \                                                        /  #
#   +------------------------------------------------------+   #

# +----------------------------------+ #
# |      Settings Configuration      | #
# +----------------------------------+ #

# +---------------+ #
# | Update Config | #
# +---------------+ #

# If you have faced any problem with the file you can create a new one by changing [Config_Version] to a different
# number, but when a new update comes out with a new configuration file(s), [Config_Version] will change resulting
# in a new file(s) for that new version while saving old files with a suffix -old to indicate they are old.
Config_Version: '${project.version}'
# We recommend to leave it true so people that got the permission will receive an update message.
Show_Update: true # This will work next update. An update will release immediately.

# +-----------------+ #
# | Language Config | #
# +-----------------+ #

# Messages language type. You can create a custom language by simply creating a folder called 'message' and inside it
# the language. You should respect the prefix of the file name, it should be message_xx.yml, and xx can be any letter
# you prefer. To switch between the languages, you enter the xx values in 'Language' and it would load that
# configuration.
# Any faulty written language names entered this attribute 'Language', then the plugin would disable. To make the plugin
# work just use any valid language. To get the list of the available languages, just enter an invalid name, and a
# message of the available list suffix would be displayed.
Language: en

# +-----------------+ #
# | Database Config | #
# +-----------------+ #
Database:
   # Specify which type of database to be used, [mysql, sqlite]
   Type: mysql
   MySQL:
      # Necessary credentials to enter your database
      Host: localhost
      Port: 3306
      Username: root
      Password: ''
   SQLite:
      # Will create a backup if the type is mysql
      Backup: true
      # Will use SQLite if unable to connect to MySQL
      Failed_MySQL: true

# +---------------+#
# | Gang Settings |#
# +---------------+#
Gang:
   Use: true
   # Allow duplicate gang names.
   Name_Duplicates: false
   Display_Name_Char: '*'
   # Hierarchy of ranks
   Rank:
      # The initial rank
      Head: "member"
      # The final rank
      Tail: "owner"
   Account:
      # When a player create a gang account his account will have the amount of money that you set.
      First_Balance: 0
      # When a player wants to create a gang account they are required to pay a fee.
      # Set it to 0, and the requirement is lifted.
      Create_Cost: 100_000
      # Sets the maximum gang money.
      Maximum_Balance: 100_000_000_000
      # The total amount of money deposit for 1 contribution.
      # ex: deposit $1 -> 0.001
      # ex: deposit $1000 -> 1
      Contribution_Rate: 1_000

# +------------------+ #
# | Economy Settings | #
# +------------------+ #

# [Money_Symbol] used as %money_symbol% prefix.
Money_Symbol: '$'
Balance_Format:
   Use: true
   Format: "%,.1f"
# [Player_Account] is for the player account.
Player_Account:
   # On Player Join his default account will have the amount of money that you set.
   First_Balance: 0
   # [Maximum_Balance] is the maximum amount of money the player can have.
   Maximum_Balance: 1_000_000
# [Bank_Account] is for the player account.
Bank_Account:
   # When a player create a bank account his account will have the amount of money that you set.
   First_Balance: 0
   # When a player wants to create a bank account they are required to pay a fee.
   # Set it to 0, and the requirement is lifted.
   Create_Cost: 5_000
   # [Maximum_Balance] is the maximum amount of money the bank can have.
   Maximum_Balance: 1_000_000_000
